// Seed data — sample dishes to show the app isn't empty
const SEED_DISHES = [
  {
    id: 'd1',
    name: 'Slow-braised short rib ragù',
    category: 'Mains',
    tags: ['italian', 'weekend', 'comfort'],
    servings: 6,
    prepTime: 30,
    cookTime: 210,
    heroPhoto: null,
    ingredients: [
      { qty: '2.5', unit: 'lb', item: 'bone-in short ribs' },
      { qty: '1', unit: 'tbsp', item: 'kosher salt' },
      { qty: '3', unit: 'tbsp', item: 'olive oil' },
      { qty: '1', unit: '', item: 'large yellow onion, diced' },
      { qty: '2', unit: '', item: 'carrots, finely diced' },
      { qty: '3', unit: 'cloves', item: 'garlic, smashed' },
      { qty: '1', unit: 'cup', item: 'red wine' },
      { qty: '28', unit: 'oz', item: 'whole peeled tomatoes' },
      { qty: '2', unit: 'sprigs', item: 'rosemary' },
      { qty: '1', unit: 'lb', item: 'pappardelle' },
    ],
    steps: [
      { text: 'Pat ribs dry and season generously with salt. Let sit 20 minutes at room temperature.', timer: null },
      { text: 'Heat oil in a heavy Dutch oven over medium-high. Sear ribs on all sides until deeply browned, 3–4 minutes per side. Transfer to a plate.', timer: 15 },
      { text: 'Reduce heat to medium. Add onion and carrots; cook until soft, about 8 minutes. Add garlic and cook 1 minute more.', timer: 10 },
      { text: 'Pour in wine, scraping up any browned bits. Simmer until reduced by half.', timer: 6 },
      { text: 'Crush tomatoes by hand into the pot. Add rosemary and return ribs with any juices. Bring to a gentle simmer.', timer: null },
      { text: 'Cover and transfer to a 300°F oven. Braise until meat falls off the bone, 2½ to 3 hours.', timer: 150 },
      { text: 'Shred the meat, discard bones and rosemary stems. Stir sauce back together.', timer: null },
      { text: 'Cook pappardelle to al dente. Toss with ragù and a splash of pasta water. Serve.', timer: 10 },
    ],
    notes: 'Julia\'s tip: make a day ahead — the flavor deepens overnight. Skim any fat from the top before reheating.',
    links: [
      { title: 'Watch the technique', url: 'youtube.com/watch?v=short-rib-ragu' },
      { title: 'Mom\'s original recipe', url: 'notes.app/kitchen/mom-ragu' },
    ],
  },
  {
    id: 'd2',
    name: 'Charred broccolini with preserved lemon',
    category: 'Sides',
    tags: ['quick', 'vegetarian', 'weeknight'],
    servings: 4,
    prepTime: 10,
    cookTime: 12,
    ingredients: [
      { qty: '1', unit: 'lb', item: 'broccolini' },
      { qty: '3', unit: 'tbsp', item: 'olive oil' },
      { qty: '', unit: '', item: 'flaky salt' },
      { qty: '1', unit: '', item: 'preserved lemon, rind minced' },
      { qty: '1/4', unit: 'cup', item: 'toasted almonds, chopped' },
      { qty: '', unit: '', item: 'chile flakes to taste' },
    ],
    steps: [
      { text: 'Preheat a large cast iron skillet over high heat until smoking.', timer: 5 },
      { text: 'Toss broccolini with 2 tbsp olive oil and salt.', timer: null },
      { text: 'Add to skillet in a single layer. Don\'t move for 3 minutes — let it char.', timer: 3 },
      { text: 'Flip and cook 2 more minutes. Stems should be tender-crisp.', timer: 2 },
      { text: 'Transfer to a plate. Drizzle with remaining oil, scatter preserved lemon, almonds, and chile.', timer: null },
    ],
    notes: 'The preserved lemon is the whole trick. Make your own once and you\'ll have it for months.',
    links: [
      { title: 'How to preserve lemons', url: 'foodblog.com/preserved-lemons' },
    ],
  },
  {
    id: 'd3',
    name: 'Miso-butter cod',
    category: 'Mains',
    tags: ['japanese', 'weeknight', 'fish'],
    servings: 2,
    prepTime: 5,
    cookTime: 15,
    ingredients: [
      { qty: '2', unit: '', item: 'cod fillets (6 oz each)' },
      { qty: '2', unit: 'tbsp', item: 'white miso' },
      { qty: '2', unit: 'tbsp', item: 'unsalted butter, softened' },
      { qty: '1', unit: 'tsp', item: 'mirin' },
      { qty: '1', unit: '', item: 'scallion, thinly sliced' },
    ],
    steps: [
      { text: 'Heat broiler to high. Line a small sheet pan with parchment.', timer: null },
      { text: 'Mash miso, butter, and mirin together with a fork.', timer: null },
      { text: 'Pat cod dry and place on sheet pan. Slather thickly with miso butter.', timer: null },
      { text: 'Broil 6 inches from heat until deeply caramelized on top and cooked through, 8–10 minutes.', timer: 9 },
      { text: 'Scatter scallions and serve with rice.', timer: null },
    ],
    notes: '',
    links: [],
  },
  {
    id: 'd4',
    name: 'Salted honey olive oil cake',
    category: 'Desserts',
    tags: ['baking', 'make-ahead'],
    servings: 10,
    prepTime: 15,
    cookTime: 45,
    ingredients: [
      { qty: '1', unit: 'cup', item: 'good olive oil' },
      { qty: '3/4', unit: 'cup', item: 'honey' },
      { qty: '3', unit: '', item: 'large eggs' },
      { qty: '1', unit: 'cup', item: 'whole milk yogurt' },
      { qty: '1.5', unit: 'cups', item: 'all-purpose flour' },
      { qty: '1', unit: 'tsp', item: 'baking powder' },
      { qty: '1/2', unit: 'tsp', item: 'baking soda' },
      { qty: '1', unit: 'tsp', item: 'flaky salt' },
    ],
    steps: [
      { text: 'Preheat oven to 350°F. Butter a 9-inch cake pan and line with parchment.', timer: null },
      { text: 'Whisk oil, honey, and eggs until smooth. Whisk in yogurt.', timer: null },
      { text: 'Fold in flour, baking powder, baking soda, and half the salt.', timer: null },
      { text: 'Pour into pan. Bake until a tester comes out with a few moist crumbs, 40–45 minutes.', timer: 42 },
      { text: 'Cool 15 minutes in pan. Invert, sprinkle with remaining salt. Best the next day.', timer: 15 },
    ],
    notes: 'Springs back more beautifully when the honey is a dark, floral one — chestnut or buckwheat if you can find it.',
    links: [],
  },
  {
    id: 'd5',
    name: 'Garlicky white beans on toast',
    category: 'Mains',
    tags: ['quick', 'vegetarian', 'pantry'],
    servings: 2,
    prepTime: 5,
    cookTime: 10,
    ingredients: [
      { qty: '1', unit: 'can', item: 'cannellini beans (15 oz), drained' },
      { qty: '4', unit: 'cloves', item: 'garlic, thinly sliced' },
      { qty: '1/4', unit: 'cup', item: 'olive oil' },
      { qty: '2', unit: 'sprigs', item: 'thyme' },
      { qty: '2', unit: 'slices', item: 'thick sourdough, toasted' },
      { qty: '', unit: '', item: 'lemon + chile flakes' },
    ],
    steps: [
      { text: 'Warm olive oil in a small skillet over medium-low. Add garlic and thyme; let it get fragrant but not brown.', timer: 4 },
      { text: 'Add beans with a splash of water. Smash about half with a fork. Simmer until creamy.', timer: 5 },
      { text: 'Spoon onto toast. Lemon, chile, more oil.', timer: null },
    ],
    notes: '',
    links: [],
  },
  {
    id: 'd6',
    name: 'Cucumber & dill tzatziki',
    category: 'Sides',
    tags: ['greek', 'no-cook', 'make-ahead'],
    servings: 6,
    prepTime: 15,
    cookTime: 0,
    ingredients: [
      { qty: '1', unit: '', item: 'English cucumber, grated' },
      { qty: '2', unit: 'cups', item: 'full-fat Greek yogurt' },
      { qty: '2', unit: 'cloves', item: 'garlic, grated' },
      { qty: '2', unit: 'tbsp', item: 'olive oil' },
      { qty: '1', unit: 'tbsp', item: 'lemon juice' },
      { qty: '2', unit: 'tbsp', item: 'fresh dill, chopped' },
    ],
    steps: [
      { text: 'Salt the grated cucumber and let drain in a sieve for 10 minutes. Squeeze hard to remove water.', timer: 10 },
      { text: 'Stir everything together. Taste and adjust salt and lemon.', timer: null },
      { text: 'Rest in the fridge at least 30 minutes before serving.', timer: 30 },
    ],
    notes: '',
    links: [],
  },
  {
    id: 'd7',
    name: 'Crispy smashed potatoes',
    category: 'Sides',
    tags: ['comfort', 'make-ahead'],
    servings: 4,
    prepTime: 5,
    cookTime: 45,
    ingredients: [
      { qty: '2', unit: 'lb', item: 'baby yukon gold potatoes' },
      { qty: '1/4', unit: 'cup', item: 'olive oil' },
      { qty: '2', unit: 'sprigs', item: 'rosemary' },
      { qty: '', unit: '', item: 'flaky salt + black pepper' },
    ],
    steps: [
      { text: 'Boil potatoes in heavily salted water until a knife slides through easily, 20 minutes.', timer: 20 },
      { text: 'Heat oven to 450°F. Drain potatoes and let steam dry for 2 minutes.', timer: 2 },
      { text: 'Arrange on a sheet pan. Press each with the bottom of a glass until it cracks but holds.', timer: null },
      { text: 'Drizzle generously with oil, scatter rosemary, salt, pepper.', timer: null },
      { text: 'Roast until deeply golden and crispy, 25–30 minutes. Don\'t flip.', timer: 27 },
    ],
    notes: '',
    links: [],
  },
  {
    id: 'd8',
    name: 'Soft scrambled eggs with chives',
    category: 'Breakfast',
    tags: ['quick', 'french', 'vegetarian'],
    servings: 2,
    prepTime: 3,
    cookTime: 5,
    ingredients: [
      { qty: '4', unit: '', item: 'large eggs' },
      { qty: '2', unit: 'tbsp', item: 'cold butter, cubed' },
      { qty: '', unit: '', item: 'salt' },
      { qty: '1', unit: 'tbsp', item: 'crème fraîche' },
      { qty: '1', unit: 'tbsp', item: 'chives, finely snipped' },
    ],
    steps: [
      { text: 'Crack eggs into a cold nonstick pan. Add half the butter.', timer: null },
      { text: 'Set over low heat and stir slowly and constantly with a rubber spatula.', timer: null },
      { text: 'When they start to set in ribbons, pull off the heat and fold in remaining butter + crème fraîche.', timer: 4 },
      { text: 'Season with salt. Top with chives. Serve immediately on warm plates.', timer: null },
    ],
    notes: 'Low heat. Patience. Never let them fully set in the pan.',
    links: [],
  },
];

const CATEGORIES = ['Mains', 'Sides', 'Desserts', 'Breakfast', 'Drinks', 'Snacks'];

// Seed pantry items
const SEED_PANTRY = [
  { id: 'p1', name: 'Olive oil',          qty: '1 bottle',   location: 'Pantry', purchased: '2026-03-20', expires: '2027-03-20', notes: '' },
  { id: 'p2', name: 'Cannellini beans',   qty: '3 cans',     location: 'Pantry', purchased: '2026-02-10', expires: '2028-02-10', notes: '' },
  { id: 'p3', name: 'Greek yogurt',       qty: '32 oz',      location: 'Fridge', purchased: '2026-04-12', expires: '2026-04-25', notes: '' },
  { id: 'p4', name: 'Cod fillets',        qty: '2',          location: 'Freezer',purchased: '2026-04-10', expires: '2026-07-10', notes: 'Wild-caught' },
  { id: 'p5', name: 'Preserved lemons',   qty: '1 jar',      location: 'Fridge', purchased: '2026-01-15', expires: '2026-12-15', notes: 'Homemade' },
  { id: 'p6', name: 'Short ribs',         qty: '2.5 lb',     location: 'Freezer',purchased: '2026-04-18', expires: '2026-04-22', notes: '' },
  { id: 'p7', name: 'Miso paste',         qty: '1 tub',      location: 'Fridge', purchased: '2025-11-02', expires: '2026-05-01', notes: 'White' },
  { id: 'p8', name: 'All-purpose flour',  qty: '5 lb',       location: 'Pantry', purchased: '2026-03-01', expires: '2027-03-01', notes: '' },
  { id: 'p9', name: 'Eggs',               qty: '8',          location: 'Fridge', purchased: '2026-04-15', expires: '2026-04-21', notes: '' },
  { id: 'p10', name: 'Honey',             qty: '1 jar',      location: 'Pantry', purchased: '2026-02-01', expires: '', notes: 'Wildflower' },
];

window.SEED_DISHES = SEED_DISHES;
window.CATEGORIES = CATEGORIES;
window.SEED_PANTRY = SEED_PANTRY;
